## Importing Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

## Reading input file

In [9]:
with open("C:\\Users\\pkuma262\\OneDrive - JNJ\\Desktop\\Anaconda_Jupyter_NoteBook\\LSTM\\IndiaUS.txt", 'r', encoding='utf-8') as myfile:
    mytext = myfile.read()

In [10]:
mytext

'Following a lavish state visit by Indian Prime Minister Narendra Modi to Washington, US President Joe Biden has called his country\'s partnership with India among the "most consequential in the world". The BBC\'s Vikas Pandey and Soutik Biswas explore the factors that contribute to the visit\'s potential in strengthening the ties between the two nations.\n\nThe US\'s relationship with India - the world\'s most populous country - is "stronger, closer and more dynamic than any time in history", Mr Biden said at the completion of a pomp-filled state visit by Mr Modi to the White House.\n\nThe remark may not be an exaggeration. "This summit suggests that the relationship has been transformed. It underscores just how broad and deep it has become in a relatively short time," says Michael Kugelman of The Wilson Center, an American think-tank.\n\nA key reason is that Washington is keen to draw India closer so that it can act as a counterbalance to China\'s growing influence in the Indo-Pacifi

## Tokenizing the text and assigning unique number to each words

In [12]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])
total_words = len(mytokenizer.word_index) + 1

In [13]:
total_words

599

In [14]:
mytokenizer.word_index

{'the': 1,
 'to': 2,
 'in': 3,
 'a': 4,
 'and': 5,
 'india': 6,
 'of': 7,
 'mr': 8,
 'us': 9,
 'is': 10,
 'modi': 11,
 'has': 12,
 'that': 13,
 'biden': 14,
 'as': 15,
 'with': 16,
 'not': 17,
 "india's": 18,
 'for': 19,
 'but': 20,
 'on': 21,
 'washington': 22,
 'an': 23,
 'it': 24,
 'says': 25,
 'will': 26,
 'are': 27,
 'indian': 28,
 'prime': 29,
 'minister': 30,
 'this': 31,
 'have': 32,
 'trade': 33,
 'visit': 34,
 'by': 35,
 'president': 36,
 'relationship': 37,
 'been': 38,
 'about': 39,
 'strategic': 40,
 'more': 41,
 'up': 42,
 'during': 43,
 'also': 44,
 'make': 45,
 'sirohi': 46,
 'china': 47,
 'air': 48,
 'force': 49,
 'state': 50,
 'his': 51,
 'ties': 52,
 'two': 53,
 'at': 54,
 'white': 55,
 'house': 56,
 'be': 57,
 'lot': 58,
 'ms': 59,
 'technology': 60,
 'jet': 61,
 'semiconductor': 62,
 'now': 63,
 'first': 64,
 'was': 65,
 'global': 66,
 'one': 67,
 'he': 68,
 'without': 69,
 'they': 70,
 'narendra': 71,
 'joe': 72,
 'world': 73,
 'potential': 74,
 'how': 75,
 'becom

## Preparing sequences

In [19]:
my_input_sequences = []

for x in mytext.split("\n"):
#     print(x)
    token_list = mytokenizer.texts_to_sequences([x])[0]
#     print(token_list)
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[: i+1]
#         print(my_n_gram_sequence)
        my_input_sequences.append(my_n_gram_sequence)

In [22]:
my_input_sequences

[[99, 4],
 [99, 4, 177],
 [99, 4, 177, 50],
 [99, 4, 177, 50, 34],
 [99, 4, 177, 50, 34, 35],
 [99, 4, 177, 50, 34, 35, 28],
 [99, 4, 177, 50, 34, 35, 28, 29],
 [99, 4, 177, 50, 34, 35, 28, 29, 30],
 [99, 4, 177, 50, 34, 35, 28, 29, 30, 71],
 [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11],
 [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2],
 [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22],
 [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9],
 [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36],
 [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72],
 [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14],
 [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14, 12],
 [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14, 12, 178],
 [99,
  4,
  177,
  50,
  34,
  35,
  28,
  29,
  30,
  71,
  11,
  2,
  22,
  9,
  36,
  72,
  14,
  12,
  178,
  51],
 [99,
  4,
  177,
  50,
  34,
  35,
  28,
  29,
  30,
  71,
  11,
  2,
  22,
  9,
  

## Preparing training data

In [20]:
max_sequence_len = max([len(x) for x in my_input_sequences])

# pad_sequences - To make sure all the length are same (my_input_sequences) for training purpose
input_sequences = np.array(pad_sequences(my_input_sequences, 
                                         maxlen = max_sequence_len, 
                                         padding = "pre"))

In [21]:
input_sequences

array([[  0,   0,   0, ...,   0,  99,   4],
       [  0,   0,   0, ...,  99,   4, 177],
       [  0,   0,   0, ...,   4, 177,  50],
       ...,
       [  0,   0,   0, ..., 176, 598,  25],
       [  0,   0,   0, ..., 598,  25,  59],
       [  0,   0,   0, ...,  25,  59,  46]])

## Breaking input_sequences into features and target

In [23]:
x = input_sequences[:, :-1]

y = input_sequences[:, -1]

In [24]:
x

array([[  0,   0,   0, ...,   0,   0,  99],
       [  0,   0,   0, ...,   0,  99,   4],
       [  0,   0,   0, ...,  99,   4, 177],
       ...,
       [  0,   0,   0, ...,   5, 176, 598],
       [  0,   0,   0, ..., 176, 598,  25],
       [  0,   0,   0, ..., 598,  25,  59]])

In [25]:
y

array([  4, 177,  50, ...,  25,  59,  46])

## Converting target to OneHot vectors

In [26]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes = total_words))

y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

## Building LSTM Model

In [27]:
# Model type is Sequential
model = Sequential()
# Embedding layer
model.add(Embedding(total_words, 100, input_length = max_sequence_len - 1))
# Building LSTM model with 150 units (neurons)
model.add(LSTM(150))
# Creating Dense layer.
# Since out target is categorical (multiclass), hence using Softmax activation
model.add(Dense(total_words, activation = "softmax")) 
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 82, 100)           59900     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 599)               90449     
                                                                 
Total params: 300,949
Trainable params: 300,949
Non-trainable params: 0
_________________________________________________________________
None


## Model Compilation

In [28]:
model.compile(loss = "categorical_crossentropy", optimizer = "adam", metrics = ["accuracy"])

## Training model

In [29]:
model.fit(x, y, epochs = 100, verbose = 1)

Epoch 1/100
43/43 [==============================] - 12s 162ms/step - loss: 6.1755 - accuracy: 0.0518
Epoch 2/100
43/43 [==============================] - 7s 155ms/step - loss: 5.7956 - accuracy: 0.0576
Epoch 3/100
43/43 [==============================] - 7s 160ms/step - loss: 5.7180 - accuracy: 0.0576
Epoch 4/100
43/43 [==============================] - 7s 155ms/step - loss: 5.6722 - accuracy: 0.0576
Epoch 5/100
43/43 [==============================] - 6s 144ms/step - loss: 5.5891 - accuracy: 0.0576
Epoch 6/100
43/43 [==============================] - 7s 151ms/step - loss: 5.4746 - accuracy: 0.0576
Epoch 7/100
43/43 [==============================] - 6s 150ms/step - loss: 5.3269 - accuracy: 0.0678
Epoch 8/100
43/43 [==============================] - 6s 148ms/step - loss: 5.1407 - accuracy: 0.0904
Epoch 9/100
43/43 [==============================] - 6s 146ms/step - loss: 4.9121 - accuracy: 0.1131
Epoch 10/100
43/43 [==============================] - 6s 147ms/step - loss: 4.6556 - accur

43/43 [==============================] - 6s 145ms/step - loss: 0.0661 - accuracy: 0.9861
Epoch 82/100
43/43 [==============================] - 6s 147ms/step - loss: 0.0644 - accuracy: 0.9861
Epoch 83/100
43/43 [==============================] - 6s 141ms/step - loss: 0.0634 - accuracy: 0.9869
Epoch 84/100
43/43 [==============================] - 6s 146ms/step - loss: 0.0625 - accuracy: 0.9854
Epoch 85/100
43/43 [==============================] - 7s 158ms/step - loss: 0.0614 - accuracy: 0.9854
Epoch 86/100
43/43 [==============================] - 6s 150ms/step - loss: 0.0594 - accuracy: 0.9876
Epoch 87/100
43/43 [==============================] - 7s 157ms/step - loss: 0.0585 - accuracy: 0.9861
Epoch 88/100
43/43 [==============================] - 7s 154ms/step - loss: 0.0569 - accuracy: 0.9869
Epoch 89/100
43/43 [==============================] - 6s 151ms/step - loss: 0.0559 - accuracy: 0.9854
Epoch 90/100
43/43 [==============================] - 7s 153ms/step - loss: 0.0557 - accuracy: 

## Predictions

In [35]:
# input_text is our input and we will be predicting predict_next_words words 

input_text = "Joe biden" 
predict_next_words= 6

# input_text = "India" 
# predict_next_words= 2

for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print("Token Number for {}: ".format(input_text), token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

Token Number for Joe biden:  [72, 14]
1/1 [==============================] - 0s 37ms/step
Token Number for Joe biden and:  [72, 14, 5]
1/1 [==============================] - 0s 34ms/step
Token Number for Joe biden and indian:  [72, 14, 5, 28]
1/1 [==============================] - 0s 36ms/step
Token Number for Joe biden and indian prime:  [72, 14, 5, 28, 29]
1/1 [==============================] - 0s 44ms/step
Token Number for Joe biden and indian prime minister:  [72, 14, 5, 28, 29, 30]
1/1 [==============================] - 0s 61ms/step
Token Number for Joe biden and indian prime minister narendra:  [72, 14, 5, 28, 29, 30, 71]
1/1 [==============================] - 0s 50ms/step
Joe biden and indian prime minister narendra modi
