## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.datasets import load_breast_cancer

In [2]:
breast_cancer = load_breast_cancer()

In [3]:
df = pd.DataFrame(breast_cancer.data, columns = breast_cancer.feature_names)

df['diagnosis'] = breast_cancer.target

df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  diagnosis  
0          0.4601                  0.11890          0  
1          0.2750                  0.08902          0  
2          0.3613                  0.08758          0  
3          0.6638                  0.17300          0  
4          0.2364                  0.07678          0  

[5 rows x 31 columns]

## Creating X and Y dataset

In [4]:
X = df.drop(columns = "diagnosis")
y = df.iloc[:,-1]

In [5]:
X.shape

(569, 30)

## Standardizing Dataset

In [6]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_scaled = sc.fit_transform(X)

## Dimenstion Reduction - PCA

In [7]:
from sklearn.decomposition import PCA

pc = PCA(n_components = 30)

pc.fit_transform(X_scaled)

pc.explained_variance_ratio_.cumsum()

array([0.44272026, 0.63243208, 0.72636371, 0.79238506, 0.84734274,
       0.88758796, 0.9100953 , 0.92598254, 0.93987903, 0.95156881,
       0.961366  , 0.97007138, 0.97811663, 0.98335029, 0.98648812,
       0.98915022, 0.99113018, 0.99288414, 0.9945334 , 0.99557204,
       0.99657114, 0.99748579, 0.99829715, 0.99889898, 0.99941502,
       0.99968761, 0.99991763, 0.99997061, 0.99999557, 1.        ])

## Finalizing PCA

In [8]:
from sklearn.decomposition import PCA

pca  = PCA(n_components = 6)

X_pca = pca.fit_transform(X_scaled)

In [9]:
print(X_pca.shape)
print(X_pca)

(569, 6)
[[ 9.19283683  1.94858307 -1.1231666   3.63373145 -1.19511193  1.41141773]
 [ 2.3878018  -3.76817174 -0.52929247  1.11826357  0.62177545  0.02866024]
 [ 5.73389628 -1.0751738  -0.55174757  0.9120826  -0.17708591  0.5414529 ]
 ...
 [ 1.25617928 -1.90229671  0.56273056 -2.08922707  1.80999134 -0.53444645]
 [10.37479406  1.6720101  -1.87702953 -2.35603083 -0.03374232  0.56793257]
 [-5.4752433  -0.67063679  1.49044293 -2.29915693 -0.18470466  1.61783568]]


In [10]:
y.shape

(569,)

## Using PCA dimension reduction in supervised Learning

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.3, shuffle=True, random_state=66)

In [12]:
from sklearn.linear_model import LogisticRegression

logit_model = LogisticRegression()

logit_model.fit(X_train,y_train)

LogisticRegression()

In [13]:
## Calcualting R-square for regressor
logit_model.score(X_test,y_test)

0.9824561403508771

In [14]:
## Calcualting R-square
logit_model.score(X_train,y_train)

0.9748743718592965

In [15]:
predicted_y = logit_model.predict(X_test)

In [16]:
from sklearn.metrics import *

accuracy_score(y_test, predicted_y) # accuracy_score of sklearn.metrics for classifier.

0.9824561403508771